/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Confetti: typeof import('./components/Confetti.vue')['default']
    FloodItGame: typeof import('./components/FloodItGame.vue')['default']
  }
}
